// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendFrame(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function StartCAN(arg1:string):Promise<void>;

export function StopCAN():Promise<void>;
