// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendFrame(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFrame'](arg1, arg2, arg3);
}

export function StartCAN(arg1) {
  return window['go']['main']['App']['StartCAN'](arg1);
}

export function StopCAN() {
  return window['go']['main']['App']['StopCAN']();
}
